### PR TITLE
Global network policy

### PR DESCRIPTION
**Pull request by adisos**

### CODE REVIEW

**Comment by adisos** [comment]
some issue: if the baseline rule is a deny rule without any protocol specified + the policies are Istio AuthorizationPolicies, then since we consider all non-TCP traffic as allowed by Istio config, we will get violations of the baseline rule for all non-TCP protocols.

**Comment by zivnevo** [comment]
> some issue: if the baseline rule is a deny rule without any protocol specified + the policies are Istio AuthorizationPolicies, then since we consider all non-TCP traffic as allowed by Istio config, we will get violations of the baseline rule for all non-TCP protocols (even if the Istio policies deny TCP traffic between the required endpoints).

I think this is very reasonable - this is indeed a violation of the rule

**Comment by adisos** [comment]
> > some issue: if the baseline rule is a deny rule without any protocol specified + the policies are Istio AuthorizationPolicies, then since we consider all non-TCP traffic as allowed by Istio config, we will get violations of the baseline rule for all non-TCP protocols (even if the Istio policies deny TCP traffic between the required endpoints).
> 
> I think this is very reasonable - this is indeed a violation of the rule

Right, but maybe there should be some warning for using a baseline rule that does not limit connections to TCP-only when being checked for an Istio config? Such a rule will always fail for an Istio-only config..
(Though we currently do not have indication of the policy types being checked, it is just sent to nca.)

**Comment by zivnevo** [comment]
> > > some issue: if the baseline rule is a deny rule without any protocol specified + the policies are Istio AuthorizationPolicies, then since we consider all non-TCP traffic as allowed by Istio config, we will get violations of the baseline rule for all non-TCP protocols (even if the Istio policies deny TCP traffic between the required endpoints).
> > 
> > 
> > I think this is very reasonable - this is indeed a violation of the rule
> 
> Right, but maybe there should be some warning for using a baseline rule that does not limit connections to TCP-only when being checked for an Istio config? Such a rule will always fail for an Istio-only config.. (Though we currently do not have indication of the policy types being checked, it is just sent to nca.)

I think the counterexample NCA will return (and which baseline-rules-verifier also shows) should be enough to explain why the rule is violated. Of course, we can be nice and provide more info, but I don't think it's urgent.

**Review by zivnevo — DISMISSED** [review]
Make sure `baseline-rules` submodule points to `master` after merge

**Review by zivnevo — APPROVED** [review]
ok

**Pull request merged**
